
const Types = {
    SET_USER:'SET_USER',
    USER_ERROR:'USER_ERROR',
    SET_PROFILE:'SET_PROFILE',
    PROFILE_ERROR:'PROFILE_ERROR',
    SET_POST:'SET_POST',
    POST_ERROR: 'POST_ERROR',
    SET_THUMBNAIL: 'SET_THUMBNAIL',
    GET_POSTS: 'GET_POSTS',
    GET_POST: 'GET_POST',
    GET_USER :'GET_USER',
    DELETE_POST: 'DELETE_POST',
    EDIT_POST: 'EDIT_POST',
    LIKE_POST: 'LIKE_POST',


}

export default Types